version: '3'

services:
  app:
    build: .
    command: sleep infinity
    volumes:
    - type: bind
      source: ..
      target: /workspace
    networks:
      - ferretdb-dev

networks:
  ferretdb-dev:
    external: true
